{side}_hand_controller:
  ros__parameters:
    update_rate: 100
    target_command_enabled: true
    target_command_close_config: 1
    target_command_open_config: 0
    movej_interpolation_type: "linear"
    home_interpolation_type: "linear"
    joints:
      - {side_}hand_finger1_joint1
      - {side_}hand_finger1_joint2
      - {side_}hand_finger1_joint3
      - {side_}hand_finger1_joint4
      - {side_}hand_finger2_joint1
      - {side_}hand_finger2_joint2
      - {side_}hand_finger2_joint3
      - {side_}hand_finger2_joint4
      - {side_}hand_finger3_joint1
      - {side_}hand_finger3_joint2
      - {side_}hand_finger3_joint3
      - {side_}hand_finger3_joint4
      - {side_}hand_finger4_joint1
      - {side_}hand_finger4_joint2
      - {side_}hand_finger4_joint3
      - {side_}hand_finger4_joint4
      - {side_}hand_finger5_joint1
      - {side_}hand_finger5_joint2
      - {side_}hand_finger5_joint3
      - {side_}hand_finger5_joint4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    home_1: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    home_2: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
    home_duration: 3.0
    movej_duration: 3.0
    hold_position_threshold: 0.1

joint_state_extra_joints:
  - {side_}hand_finger1_joint1
  - {side_}hand_finger1_joint2
  - {side_}hand_finger1_joint3
  - {side_}hand_finger1_joint4
  - {side_}hand_finger2_joint1
  - {side_}hand_finger2_joint2
  - {side_}hand_finger2_joint3
  - {side_}hand_finger2_joint4
  - {side_}hand_finger3_joint1
  - {side_}hand_finger3_joint2
  - {side_}hand_finger3_joint3
  - {side_}hand_finger3_joint4
  - {side_}hand_finger4_joint1
  - {side_}hand_finger4_joint2
  - {side_}hand_finger4_joint3
  - {side_}hand_finger4_joint4
  - {side_}hand_finger5_joint1
  - {side_}hand_finger5_joint2
  - {side_}hand_finger5_joint3
  - {side_}hand_finger5_joint4
